// Auto-generated by scripts/gen-perf-fixture.mjs. Do not edit by hand.
import { z } from 'zod';

const server = {
    tool(_name, _schema, handler) {
        return handler;
    },
};

server.tool('tool_038', { input: z.object({ value: z.string().min(1).max(100) }) }, async (input) => {
    console.info('tool_038 invoked');
    return { ok: true, value: input.value };
});

process.on('uncaughtException', (err) => {
    console.error('uncaught', err);
});
